// ============================================================
// puzzles.ts — All puzzle definitions grouped by difficulty
// ============================================================

import { Puzzle } from "./types";

// ── Easy (5×5) ──────────────────────────────────────────────
const easyPuzzles: Puzzle[] = [
  {
    id: "easy-1",
    name: "Sunrise",
    difficulty: "easy",
    size: 5,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 4, col: 4 } },
      { color: "blue",   position: { row: 0, col: 4 } },
      { color: "blue",   position: { row: 4, col: 0 } },
      { color: "green",  position: { row: 2, col: 1 } },
      { color: "green",  position: { row: 2, col: 3 } },
      { color: "yellow", position: { row: 1, col: 2 } },
      { color: "yellow", position: { row: 3, col: 2 } },
    ],
  },
  {
    id: "easy-2",
    name: "Cross",
    difficulty: "easy",
    size: 5,
    dots: [
      { color: "red",    position: { row: 0, col: 2 } },
      { color: "red",    position: { row: 4, col: 2 } },
      { color: "blue",   position: { row: 2, col: 0 } },
      { color: "blue",   position: { row: 2, col: 4 } },
      { color: "yellow", position: { row: 0, col: 0 } },
      { color: "yellow", position: { row: 4, col: 4 } },
      { color: "green",  position: { row: 1, col: 1 } },
      { color: "green",  position: { row: 3, col: 3 } },
    ],
  },
  {
    id: "easy-3",
    name: "Square",
    difficulty: "easy",
    size: 5,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 0, col: 4 } },
      { color: "blue",   position: { row: 4, col: 0 } },
      { color: "blue",   position: { row: 4, col: 4 } },
      { color: "green",  position: { row: 1, col: 2 } },
      { color: "green",  position: { row: 3, col: 2 } },
      { color: "orange", position: { row: 2, col: 1 } },
      { color: "orange", position: { row: 2, col: 3 } },
    ],
  },
  {
    id: "easy-4",
    name: "Zigzag",
    difficulty: "easy",
    size: 5,
    dots: [
      { color: "red",    position: { row: 0, col: 1 } },
      { color: "red",    position: { row: 4, col: 3 } },
      { color: "blue",   position: { row: 0, col: 3 } },
      { color: "blue",   position: { row: 4, col: 1 } },
      { color: "yellow", position: { row: 2, col: 0 } },
      { color: "yellow", position: { row: 2, col: 4 } },
      { color: "purple", position: { row: 1, col: 2 } },
      { color: "purple", position: { row: 3, col: 2 } },
    ],
  },
  {
    id: "easy-5",
    name: "Diamond",
    difficulty: "easy",
    size: 5,
    dots: [
      { color: "red",    position: { row: 0, col: 2 } },
      { color: "red",    position: { row: 4, col: 2 } },
      { color: "blue",   position: { row: 2, col: 0 } },
      { color: "blue",   position: { row: 2, col: 4 } },
      { color: "green",  position: { row: 1, col: 1 } },
      { color: "green",  position: { row: 3, col: 3 } },
      { color: "pink",   position: { row: 1, col: 3 } },
      { color: "pink",   position: { row: 3, col: 1 } },
    ],
  },
];

// ── Medium (7×7) ─────────────────────────────────────────────
const mediumPuzzles: Puzzle[] = [
  {
    id: "medium-1",
    name: "Labyrinth",
    difficulty: "medium",
    size: 7,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 6, col: 6 } },
      { color: "blue",   position: { row: 0, col: 6 } },
      { color: "blue",   position: { row: 6, col: 0 } },
      { color: "green",  position: { row: 0, col: 3 } },
      { color: "green",  position: { row: 6, col: 3 } },
      { color: "yellow", position: { row: 3, col: 0 } },
      { color: "yellow", position: { row: 3, col: 6 } },
      { color: "orange", position: { row: 1, col: 2 } },
      { color: "orange", position: { row: 5, col: 4 } },
      { color: "purple", position: { row: 2, col: 5 } },
      { color: "purple", position: { row: 4, col: 1 } },
    ],
  },
  {
    id: "medium-2",
    name: "Helix",
    difficulty: "medium",
    size: 7,
    dots: [
      { color: "red",    position: { row: 0, col: 1 } },
      { color: "red",    position: { row: 5, col: 5 } },
      { color: "blue",   position: { row: 0, col: 5 } },
      { color: "blue",   position: { row: 5, col: 1 } },
      { color: "green",  position: { row: 1, col: 3 } },
      { color: "green",  position: { row: 6, col: 3 } },
      { color: "yellow", position: { row: 2, col: 0 } },
      { color: "yellow", position: { row: 4, col: 6 } },
      { color: "orange", position: { row: 3, col: 2 } },
      { color: "orange", position: { row: 3, col: 4 } },
      { color: "pink",   position: { row: 6, col: 0 } },
      { color: "pink",   position: { row: 6, col: 6 } },
    ],
  },
  {
    id: "medium-3",
    name: "Vortex",
    difficulty: "medium",
    size: 7,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 3, col: 3 } },
      { color: "blue",   position: { row: 0, col: 6 } },
      { color: "blue",   position: { row: 6, col: 0 } },
      { color: "green",  position: { row: 1, col: 4 } },
      { color: "green",  position: { row: 5, col: 2 } },
      { color: "yellow", position: { row: 2, col: 1 } },
      { color: "yellow", position: { row: 6, col: 5 } },
      { color: "orange", position: { row: 4, col: 0 } },
      { color: "orange", position: { row: 4, col: 6 } },
      { color: "purple", position: { row: 6, col: 3 } },
      { color: "purple", position: { row: 0, col: 3 } },
    ],
  },
  {
    id: "medium-4",
    name: "Spiral",
    difficulty: "medium",
    size: 7,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 6, col: 6 } },
      { color: "blue",   position: { row: 0, col: 2 } },
      { color: "blue",   position: { row: 5, col: 5 } },
      { color: "green",  position: { row: 0, col: 4 } },
      { color: "green",  position: { row: 4, col: 6 } },
      { color: "yellow", position: { row: 2, col: 6 } },
      { color: "yellow", position: { row: 6, col: 2 } },
      { color: "pink",   position: { row: 2, col: 0 } },
      { color: "pink",   position: { row: 6, col: 4 } },
      { color: "cyan",   position: { row: 3, col: 3 } },
      { color: "cyan",   position: { row: 5, col: 1 } },
    ],
  },
  {
    id: "medium-5",
    name: "Bridge",
    difficulty: "medium",
    size: 7,
    dots: [
      { color: "red",    position: { row: 1, col: 0 } },
      { color: "red",    position: { row: 1, col: 6 } },
      { color: "blue",   position: { row: 5, col: 0 } },
      { color: "blue",   position: { row: 5, col: 6 } },
      { color: "green",  position: { row: 0, col: 3 } },
      { color: "green",  position: { row: 6, col: 3 } },
      { color: "yellow", position: { row: 2, col: 2 } },
      { color: "yellow", position: { row: 4, col: 4 } },
      { color: "orange", position: { row: 2, col: 4 } },
      { color: "orange", position: { row: 4, col: 2 } },
      { color: "purple", position: { row: 3, col: 1 } },
      { color: "purple", position: { row: 3, col: 5 } },
    ],
  },
];

// ── Hard (9×9) ───────────────────────────────────────────────
const hardPuzzles: Puzzle[] = [
  {
    id: "hard-1",
    name: "Megamaze",
    difficulty: "hard",
    size: 9,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 8, col: 8 } },
      { color: "blue",   position: { row: 0, col: 8 } },
      { color: "blue",   position: { row: 8, col: 0 } },
      { color: "green",  position: { row: 0, col: 4 } },
      { color: "green",  position: { row: 8, col: 4 } },
      { color: "yellow", position: { row: 4, col: 0 } },
      { color: "yellow", position: { row: 4, col: 8 } },
      { color: "orange", position: { row: 1, col: 3 } },
      { color: "orange", position: { row: 7, col: 5 } },
      { color: "purple", position: { row: 2, col: 6 } },
      { color: "purple", position: { row: 6, col: 2 } },
      { color: "pink",   position: { row: 3, col: 1 } },
      { color: "pink",   position: { row: 5, col: 7 } },
      { color: "cyan",   position: { row: 1, col: 7 } },
      { color: "cyan",   position: { row: 7, col: 1 } },
    ],
  },
  {
    id: "hard-2",
    name: "Nexus",
    difficulty: "hard",
    size: 9,
    dots: [
      { color: "red",    position: { row: 0, col: 2 } },
      { color: "red",    position: { row: 8, col: 6 } },
      { color: "blue",   position: { row: 0, col: 6 } },
      { color: "blue",   position: { row: 8, col: 2 } },
      { color: "green",  position: { row: 2, col: 0 } },
      { color: "green",  position: { row: 6, col: 8 } },
      { color: "yellow", position: { row: 2, col: 8 } },
      { color: "yellow", position: { row: 6, col: 0 } },
      { color: "orange", position: { row: 4, col: 1 } },
      { color: "orange", position: { row: 4, col: 7 } },
      { color: "purple", position: { row: 1, col: 4 } },
      { color: "purple", position: { row: 7, col: 4 } },
      { color: "pink",   position: { row: 3, col: 3 } },
      { color: "pink",   position: { row: 5, col: 5 } },
      { color: "cyan",   position: { row: 0, col: 0 } },
      { color: "cyan",   position: { row: 8, col: 8 } },
    ],
  },
  {
    id: "hard-3",
    name: "Galaxy",
    difficulty: "hard",
    size: 9,
    dots: [
      { color: "red",    position: { row: 0, col: 1 } },
      { color: "red",    position: { row: 7, col: 6 } },
      { color: "blue",   position: { row: 0, col: 7 } },
      { color: "blue",   position: { row: 7, col: 0 } },
      { color: "green",  position: { row: 1, col: 5 } },
      { color: "green",  position: { row: 8, col: 2 } },
      { color: "yellow", position: { row: 3, col: 0 } },
      { color: "yellow", position: { row: 5, col: 8 } },
      { color: "orange", position: { row: 0, col: 3 } },
      { color: "orange", position: { row: 8, col: 6 } },
      { color: "purple", position: { row: 2, col: 8 } },
      { color: "purple", position: { row: 6, col: 1 } },
      { color: "pink",   position: { row: 4, col: 4 } },
      { color: "pink",   position: { row: 8, col: 8 } },
      { color: "maroon", position: { row: 1, col: 2 } },
      { color: "maroon", position: { row: 6, col: 7 } },
    ],
  },
  {
    id: "hard-4",
    name: "Wormhole",
    difficulty: "hard",
    size: 9,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 4, col: 4 } },
      { color: "blue",   position: { row: 0, col: 4 } },
      { color: "blue",   position: { row: 8, col: 0 } },
      { color: "green",  position: { row: 0, col: 8 } },
      { color: "green",  position: { row: 8, col: 4 } },
      { color: "yellow", position: { row: 4, col: 0 } },
      { color: "yellow", position: { row: 4, col: 8 } },
      { color: "orange", position: { row: 8, col: 8 } },
      { color: "orange", position: { row: 2, col: 6 } },
      { color: "purple", position: { row: 1, col: 2 } },
      { color: "purple", position: { row: 7, col: 6 } },
      { color: "pink",   position: { row: 6, col: 2 } },
      { color: "pink",   position: { row: 2, col: 8 } },
      { color: "cyan",   position: { row: 3, col: 5 } },
      { color: "cyan",   position: { row: 6, col: 5 } },
    ],
  },
  {
    id: "hard-5",
    name: "Supernova",
    difficulty: "hard",
    size: 9,
    dots: [
      { color: "red",    position: { row: 0, col: 0 } },
      { color: "red",    position: { row: 8, col: 8 } },
      { color: "blue",   position: { row: 0, col: 3 } },
      { color: "blue",   position: { row: 3, col: 8 } },
      { color: "green",  position: { row: 3, col: 0 } },
      { color: "green",  position: { row: 8, col: 5 } },
      { color: "yellow", position: { row: 0, col: 6 } },
      { color: "yellow", position: { row: 5, col: 0 } },
      { color: "orange", position: { row: 6, col: 8 } },
      { color: "orange", position: { row: 8, col: 2 } },
      { color: "purple", position: { row: 2, col: 2 } },
      { color: "purple", position: { row: 7, col: 7 } },
      { color: "pink",   position: { row: 2, col: 6 } },
      { color: "pink",   position: { row: 6, col: 2 } },
      { color: "cyan",   position: { row: 5, col: 4 } },
      { color: "cyan",   position: { row: 4, col: 7 } },
    ],
  },
];

/** All puzzles, keyed by difficulty */
export const PUZZLES: Record<string, Puzzle[]> = {
  easy:   easyPuzzles,
  medium: mediumPuzzles,
  hard:   hardPuzzles,
};

/** Get a puzzle by id */
export function getPuzzleById(id: string): Puzzle | undefined {
  return Object.values(PUZZLES)
    .flat()
    .find((p) => p.id === id);
}
